### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by LoganTheBean** [Toory/cube-timer-cli#2]
I hit enter and it doesn't start.
IDK if the keyboard module doesn't work or what because I've tried on multiple machines.

Sorry I'm being vague I'm like super tired.

**Comment by LoganTheBean** [comment]
File "onehanded_times.csv" not found, creating new one
------------------------------
------------TIMER-------------
------------------------------
        Solves: 0
------------------------------
  Current           Best
------------------------------
------------------------------
Error: stdout: b'', stderr: b''
------------------------------
--------CUBE TIMER CLI--------
------------------------------
------------------------------
 1. Timer.
 2. Print last solves.
 3. Import from Twisty Timer
 4. Exit.
>>

**Comment by Toory** [comment]
Sorry for very late reply, if you are still interested:
Are you running the script with sudo? (required by the keyboard module)
If that's not the reason, try re-cloning the repo and running `pip install -r requirements.txt` might be a problem of updating dependencies.

**Comment by LoganTheBean** [comment]
I can't believe that it's been a year. Holy crap.
Well, I never knew what was causing the problem so I made my own timer, which I lost when I upgraded to Ubuntu 18.04. Today I just reinstalled this after your reply, and with the new version of Ubuntu, it (magically) got fixed. Huh. The only hiccup was one of the dependencies for PyTwistyScrambler which was easy to figure out (six). Thanks for your help.

**Comment by Toory** [comment]
> I can't believe that it's been a year. Holy crap.
> Well, I never knew what was causing the problem so I made my own timer, which I lost when I upgraded to Ubuntu 18.04. Today I just reinstalled this after your reply, and with the new version of Ubuntu, it (magically) got fixed. Huh. The only hiccup was one of the dependencies for PyTwistyScrambler which was easy to figure out (six). Thanks for your help.

Glad I could help!
